name: Publish

on:
  workflow_run:
    workflows: ["Lint and test"]
    types:
      - completed
jobs:
  build_and_publish:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish package
        if: github.event_name == 'release' && github.event.action == 'created'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
